// Libellés fixes du blog (pages et composants des articles), en français et en anglais.
import type { Lang } from './i18n';

export const blogUi = {
  fr: {
    dateLocale: 'fr-FR',
    home: 'Accueil',
    by: 'Par',
    updated: 'mis à jour le',
    minutes: (n: number) => `${n} min de lecture`,
    faq: 'Questions fréquentes',
    related: 'Nos services liés à cet article',
    authorAria: 'L’auteur',
    authorRole: 'Cofondateur de SHYFT. Accompagne les PME et artisans sur Google, Maps et la publicité locale.',
    linkedin: (name: string) => `Suivre ${name} sur LinkedIn`,
    finalCta: {
      k: 'Audit offert',
      titre: 'Voyez où vous en êtes, ',
      titreEm: 'gratuitement',
      texte: 'Votre visibilité sur Google et Maps, vos publicités, votre site et votre suivi des demandes, analysés en 24 h. Sans engagement.',
    },
    audit: 'Recevoir mon audit offert',
    appel: 'Réserver un appel de 30 min',
    quiz: {
      meta: (n: number) => `Quiz · ${n} questions · 1 min`,
      question: (i: number, n: number) => `Question ${i} sur ${n}`,
      reponses: ['Oui', 'En partie', 'Non'],
      priorites: 'Vos priorités',
      refaire: 'Refaire le quiz',
    },
    encadre: { essentiel: 'Ce qu’il faut retenir', astuce: 'Astuce', attention: 'Attention', exemple: 'Exemple' },
    lireArticle: 'Lire l’article',
    geo: { top: 'Top 3 : visible dans le bloc Maps', mid: '4 à 10 : visible en faisant défiler', low: 'Au-delà de 10 : quasi invisible' },
    sms: { de: 'Message envoyé à votre client', legende: 'Exemple de message à adapter. Le lien se copie depuis votre fiche, bouton « Demander des avis ».' },
    index: {
      title: 'Blog SHYFT | Acquisition, SEO et Google Ads pour PME',
      description: 'Conseils concrets pour les PME et négoces BTP : SEO local, Google Ads, Meta Ads, sites qui convertissent, tracking des conversions et automatisation IA.',
      h1: 'Blog acquisition et marketing digital pour PME',
      titre: 'Ce qui fait ',
      titreEm: 'vraiment',
      titreFin: ' venir des clients',
      lead: 'SEO local, Google Ads, Meta Ads, sites, tracking et IA : des réponses concrètes aux questions que se posent les dirigeants de PME.',
      articles: 'Articles',
      vide: 'Les premiers articles arrivent bientôt.',
    },
  },
  en: {
    dateLocale: 'en-US',
    home: 'Home',
    by: 'By',
    updated: 'updated',
    minutes: (n: number) => `${n} min read`,
    faq: 'Frequently asked questions',
    related: 'Related services',
    authorAria: 'About the author',
    authorRole: 'Co-founder of SHYFT. Helps businesses grow on Google, Google Maps and local advertising.',
    linkedin: (name: string) => `Follow ${name} on LinkedIn`,
    finalCta: {
      k: 'Free audit',
      titre: 'See where you stand, ',
      titreEm: 'for free',
      texte: 'Your visibility on Google and Maps, your ads, your website and your lead tracking, reviewed within 24 hours. No commitment.',
    },
    audit: 'Get my free audit',
    appel: 'Book a 30-min call',
    quiz: {
      meta: (n: number) => `Quiz · ${n} questions · 1 min`,
      question: (i: number, n: number) => `Question ${i} of ${n}`,
      reponses: ['Yes', 'Partly', 'No'],
      priorites: 'Your priorities',
      refaire: 'Retake the quiz',
    },
    encadre: { essentiel: 'Key takeaways', astuce: 'Tip', attention: 'Watch out', exemple: 'Example' },
    lireArticle: 'Read the article',
    geo: { top: 'Top 3: visible in the Maps pack', mid: '4 to 10: visible after scrolling', low: 'Beyond 10: practically invisible' },
    sms: { de: 'Text sent to your customer', legende: 'Sample message to adapt. Copy the link from your profile, “Ask for reviews” button.' },
    index: {
      title: 'SHYFT Blog | Local SEO, Google Ads & Growth Marketing',
      description: 'Practical advice for businesses: local SEO, Google Business Profile, Google Ads, Meta Ads, websites that convert, conversion tracking and AI automation.',
      h1: 'Growth marketing blog',
      titre: 'What ',
      titreEm: 'actually',
      titreFin: ' brings in customers',
      lead: 'Local SEO, Google Ads, Meta Ads, websites, tracking and AI: straight answers to the questions business owners ask.',
      articles: 'Articles',
      vide: 'The first articles are coming soon.',
    },
  },
} as const;

export type BlogUi = (typeof blogUi)[Lang];
