from html import escape

DATA = {
'location-de-materiel': dict(leads=40,rate=25,value=450,client='locations conclues',unit='Montant moyen d’une location HT (€)',result='CA potentiel des locations',intro='Nous générons des demandes de location qualifiées et optimisons leur conversion en réservations pour développer votre chiffre d’affaires.',seo='Pages par matériel et ville : mini-pelle, nacelle, échafaudage. Une réponse précise aux recherches dans votre zone de livraison.',ads='Campagnes sur les locations recherchées, ciblées sur votre rayon de livraison et les matériels disponibles.',google='Fiches de vos agences : catégories, matériels, horaires, photos et collecte d’avis après location. Faciliter l’appel et la demande locale.',conversion='Formulaire avec matériel, dates et lieu de livraison. Suivi des appels, réponse rapide et relances jusqu’à la réservation.',follow='Demandes reçues → demandes qualifiées → locations conclues → CA de location.',note='Montant total des locations conclues à partir de ce groupe de prospects, sans supposer de location récurrente.'),
'reseaux-de-franchise': dict(leads=20,rate=5,value=20000,client='signatures de franchise',unit='Droit d’entrée moyen HT (€)',result='Droits d’entrée potentiels',intro='Nous générons des candidatures qualifiées et structurons leur suivi jusqu’à la signature pour développer votre réseau et ses revenus.',seo='Pages sur votre concept, l’investissement et les territoires : attirer des candidats qui cherchent une franchise dans votre secteur.',ads='Campagnes Google Ads sur les intentions de création et de franchise, complétées par Meta Ads pour faire découvrir votre enseigne.',google='Optimisation des fiches des établissements pour soutenir leur acquisition locale. Un levier distinct du recrutement de franchisés.',conversion='Qualification sur apport, zone et délai. Candidatures dans le CRM, dédoublonnage et relances jusqu’au rendez-vous développeur.',follow='Candidatures → profils qualifiés → rendez-vous → signatures de franchise.',note='Simulation des seuls droits d’entrée à la signature. Elle exclut les redevances futures et le CA des franchisés ; le recrutement peut prendre plusieurs mois.'),
'renovation-artisans': dict(leads=30,rate=20,value=8000,client='chantiers signés',unit='Montant moyen d’un chantier HT (€)',result='CA potentiel des chantiers',intro='Nous générons des demandes de devis qualifiées et améliorons leur suivi pour vous aider à signer davantage de chantiers et développer votre chiffre d’affaires.',seo='Pages par métier et commune, illustrées par vos réalisations : être trouvé sur les travaux que vous souhaitez réaliser.',ads='Campagnes Google Ads sur vos prestations prioritaires, avec ciblage géographique et suivi des demandes de devis.',google='Services, zone d’intervention, photos de vrais chantiers et avis clients : donner des raisons de choisir votre entreprise.',conversion='Qualification du type de travaux, de la surface, du budget et du délai. Prise de rendez-vous et relance des devis non signés.',follow='Demandes de devis → projets qualifiés → visites techniques → chantiers signés.',note='Valeur des chantiers signés issus de ces prospects, avant coûts et selon leur calendrier de réalisation. Ce n’est pas un encaissement immédiat.'),
'immobilier': dict(leads=20,rate=10,value=6000,client='ventes finalisées',unit='Honoraires moyens par vente HT (€)',result='Honoraires potentiels',intro='Nous générons des contacts vendeurs qualifiés et optimisons le parcours jusqu’au mandat, puis le suivi des ventes qui créent votre chiffre d’affaires.',seo='Pages de quartiers et contenus pour les propriétaires vendeurs : faire connaître votre expertise locale au moment du projet.',ads='Campagnes Google Ads orientées estimation et vente, sur les communes et types de biens que vous recherchez.',google='Fiche de l’agence, services, photos, horaires et avis : faciliter la découverte locale et la prise de contact.',conversion='Formulaire sur le bien et le calendrier. Suivi du contact, rendez-vous d’estimation, mandat et issue de la vente dans le CRM.',follow='Contacts vendeurs → estimations → mandats → ventes finalisées.',note='Le taux porte ici sur les ventes effectivement finalisées, pas les mandats. Seuls les honoraires sont comptés, jamais le prix du bien ; le cycle peut durer plusieurs mois.'),
'services-a-domicile': dict(leads=30,rate=30,value=300,client='nouveaux clients',unit='CA moyen du premier mois par client HT (€)',result='CA potentiel du premier mois',intro='Nous générons des demandes locales qualifiées et facilitons leur conversion en clients pour développer votre activité selon les capacités de vos équipes.',seo='Pages par service et commune d’intervention pour répondre aux besoins concrets des familles proches de vos agences.',ads='Campagnes Google Ads sur les prestations et zones où vous pouvez accueillir de nouveaux clients.',google='Fiches des agences : prestations, horaires, photos et avis. Faciliter les appels des familles dans votre secteur.',conversion='Qualification du besoin, de la fréquence et de l’adresse. Rappel, rendez-vous d’évaluation et suivi jusqu’au démarrage du service.',follow='Demandes locales → besoins qualifiés → évaluations → nouveaux clients actifs.',note='CA du premier mois de service des nouveaux clients. Aucune durée de fidélité ni reconduction future n’est supposée.'),
'commerces-multi-sites': dict(leads=100,rate=20,value=120,client='clients ayant acheté',unit='Panier moyen du premier achat HT (€)',result='CA potentiel des premiers achats',intro='Nous générons des contacts locaux et optimisons leur conversion en clients, avec un suivi du chiffre d’affaires établissement par établissement.',seo='Une page utile par établissement : offre, informations locales et parcours de contact propres à chaque adresse.',ads='Campagnes Google Ads par zone de chalandise, avec budgets et suivi séparés pour identifier les points de vente qui performent.',google='Optimisation des fiches du réseau : catégories, horaires, photos, services et réponses aux avis, avec une cohérence de marque.',conversion='Réservation ou demande simplifiée, réponse locale et rapprochement avec les achats lorsque vos outils le permettent.',follow='Contacts locaux → réservations ou visites → achats confirmés → CA par établissement.',note='CA des premiers achats attribués aux contacts, sur le périmètre choisi. Les achats répétés et les visiteurs non identifiés sont exclus.')
}

def number(n):
 return f'{n:,.0f}'.replace(',', ' ')

def growth(s):
 d=DATA[s['slug']]
 clients=d['leads']*d['rate']/100
 revenue=clients*d['value']
 return f'''<section class="block growth-section" id="potentiel"><div class="wrap"><div class="section-top"><div><div class="kicker">Des prospects. Des clients. Du chiffre d’affaires.</div><h2 class="title">Ce que de nouveaux clients<br>peuvent changer pour vous.</h2></div><p class="sub">Rendez votre acquisition concrète. <br>Ajustez les hypothèses avec vos propres chiffres.</p></div><div class="growth-calculator" data-growth><div class="growth-inputs"><span class="simulation-label">Simulation illustrative · pas un résultat client</span><h3>Partons de votre activité.</h3><label for="growth-leads">Nombre de prospects qualifiés<input id="growth-leads" data-input="leads" type="number" min="0" max="100000" step="1" value="{d['leads']}" required></label><label for="growth-rate">Taux de transformation en {d['client']} (%)<input id="growth-rate" data-input="rate" type="number" min="0" max="100" step="0.1" value="{d['rate']}" required></label><label for="growth-value">{d['unit']}<input id="growth-value" data-input="value" type="number" min="0" max="10000000" step="1" value="{d['value']}" required></label><p class="growth-hint">Valeurs de démonstration librement choisies, sans référence à une moyenne du marché. Utilisez un même groupe de prospects suivi jusqu’à l’issue commerciale.</p></div><div class="growth-results" aria-live="polite" aria-atomic="true"><div class="growth-funnel"><div><span>01 · Acquisition</span><strong data-output="leads">{d['leads']}</strong><p>prospects qualifiés</p></div><span class="funnel-arrow" aria-hidden="true">→</span><div><span>02 · Conversion</span><strong data-output="clients">{number(clients)}</strong><p>{d['client']}</p></div></div><div class="growth-revenue"><span>03 · {d['result']}</span><strong><span data-output="revenue">{number(revenue)}</span> <small>€ HT</small></strong><p data-output="formula">{d['leads']} prospects × {d['rate']} % × {number(d['value'])} €</p></div><p class="growth-note">{d['note']} Le CA n’est pas une marge : budgets publicitaires, honoraires et coûts d’exploitation ne sont pas déduits. Aucune performance n’est garantie.</p><p class="growth-error" role="status" hidden>Complétez les trois valeurs : nombres positifs ou nuls, taux compris entre 0 et 100 %.</p></div></div><div class="growth-next"><span>On valide les hypothèses et les objectifs pendant votre audit.</span><a class="text-link" href="#contact">Recevoir mon audit offert ↗</a></div></div></section>'''

def channels(s):
 d=DATA[s['slug']]
 entries=[('SEO & référencement naturel','Capter une recherche utile',d['seo']),('Google Ads','Générer des prospects ciblés',d['ads']),('Fiche Google / Google My Business','Convertir la proximité en contacts',d['google']),('Optimisation de l’acquisition','Transformer les prospects en clients',d['conversion'])]
 cards=''.join(f'<article class="channel-card"><span class="channel-number">0{i+1} ↗</span><h3>{name}</h3><h4>{title}</h4><p>{text}</p></article>' for i,(name,title,text) in enumerate(entries))
 return '<section class="block expertise-section"><div class="wrap"><div class="kicker">Comment on génère vos opportunités</div><h2 class="title">Quatre leviers.<br>Un objectif : vos nouveaux clients.</h2><p class="sub">On relie votre visibilité, les demandes reçues et leur transformation commerciale. Chaque levier répond à une étape précise.</p><div class="channel-grid">'+cards+'</div></div></section>'

# Mesure & suivi : trois indicateurs par secteur et la source de chaque chiffre.
MEASURE = {
'location-de-materiel': [('Demandes de location qualifiées','Comptées dans votre CRM, avec la source de chaque demande.'),('Coût par demande','Google Ads et Analytics, par matériel et par campagne.'),('Visibilité par matériel et par ville','Search Console : requêtes, positions et pages qui sortent.')],
'reseaux-de-franchise': [('Candidatures qualifiées','Dans votre CRM, avec apport, zone et délai renseignés.'),('Coût par rendez-vous','Meta Ads, Google Ads et Analytics, par région et par campagne.'),('Part des profils répondant aux critères','Tableau de bord partagé, mis à jour à chaque qualification.')],
'renovation-artisans': [('Devis qualifiés reçus','Dans votre CRM, avec type de travaux, budget et délai.'),('Coût par devis qualifié','Google Ads et Analytics, par prestation et par commune.'),('Rendez-vous de visite technique','Tableau de bord partagé, du devis au chantier signé.')],
'immobilier': [('Contacts vendeurs qualifiés','Dans votre CRM, avec le bien et le calendrier du projet.'),('Coût par contact vendeur','Google Ads et Analytics, par commune et par campagne.'),('Rendez-vous d’estimation','Tableau de bord partagé, de l’estimation au mandat.')],
'services-a-domicile': [('Demandes dans votre zone','Dans votre CRM, avec le besoin, la fréquence et l’adresse.'),('Coût par contact qualifié','Google Ads et Analytics, par prestation et par agence.'),('Rendez-vous d’évaluation','Tableau de bord par agence, avec une vue pour le siège.')],
'commerces-multi-sites': [('Contacts par établissement','Dans votre CRM, rattachés à chaque adresse.'),('Coût par contact local','Google Ads et Analytics, par zone de chalandise.'),('Réservations ou rendez-vous','Tableau de bord par point de vente, avec une vue réseau.')]
}
TOOLS = ['Search Console','Google Analytics','Tableau de bord partagé','CRM','Emailing']

def measure(s):
 cards=''.join(f'<article><span>◎</span><h3>{m}</h3><p>{how}</p></article>' for m,how in MEASURE[s['slug']])
 tools=''.join(f'<li>{t}</li>' for t in TOOLS)
 return f'<section class="block" id="mesure"><div class="wrap"><div class="section-top"><div><div class="kicker">Mesure &amp; suivi</div><h2 class="title">Ce qu’on installe<br>pour mesurer.</h2></div><p class="sub">Trois indicateurs suivis avec vos outils,<br>du premier contact au chiffre d’affaires.</p></div><div class="metric-grid">{cards}</div><div class="measure-stack"><span class="kicker">Installé dans vos comptes</span><ul>{tools}</ul><p>Vous gardez tout, même si on arrête.</p></div><div class="sector-pay"><div><div class="kicker">Un modèle aligné</div><h2>Une rémunération par<br>{s["pay"]}.</h2></div><p>On fixe ensemble les critères et les conditions avant le lancement. Le budget publicitaire reste sur votre compte. On commence par un test de 60 jours sur un périmètre réduit.</p></div></div></section>'

# Ouverture des pages métier : le marché vu par les futurs clients, puis le parcours d'une demande.
WHO = {'location-de-materiel':'Vos futurs clients','reseaux-de-franchise':'Vos futurs franchisés','renovation-artisans':'Vos futurs clients','immobilier':'Vos futurs vendeurs','services-a-domicile':'Les familles','commerces-multi-sites':'Vos futurs clients'}
# Exemples de recherches (sans volume) : requête, ce qu'elle révèle, canal où elle apparaît.
SEARCHES = {
'location-de-materiel': [('location nacelle 12 m + votre ville','Un artisan, un chantier la semaine prochaine.','Google'),('louer une mini-pelle le week-end','Un particulier qui compare les prix et les horaires.','Google'),('loueur de matériel ouvert le samedi','Une recherche sur la carte, depuis un téléphone.','Fiche Google')],
'reseaux-de-franchise': [('ouvrir une franchise + votre secteur','Un porteur de projet qui compare les enseignes.','Google'),('devenir franchisé avec 100 000 € d’apport','Un candidat qui vérifie s’il entre dans vos critères.','Google'),('témoignage de franchisé + votre enseigne','Un profil qui hésite encore et cherche des preuves.','Meta')],
'renovation-artisans': [('rénovation salle de bain + votre ville','Un projet précis, souvent avec un budget en tête.','Google'),('prix extension maison 30 m²','Un propriétaire qui se renseigne avant de demander un devis.','Google'),('artisan rénovation près de moi, avis','Une comparaison sur la carte et sur les avis clients.','Fiche Google')],
'immobilier': [('estimation appartement + votre quartier','Un propriétaire qui prépare une vente.','Google'),('combien vaut ma maison à + votre ville','Une première recherche, avant de contacter une agence.','Google'),('agence immobilière + votre commune, avis','Le choix entre trois agences, sur la carte.','Fiche Google')],
'services-a-domicile': [('aide à domicile + votre ville','Une famille qui cherche une agence proche, vite.','Google'),('ménage à domicile tarif horaire','Un besoin régulier, une comparaison des prix.','Google'),('agence de services à domicile près de moi','Une recherche sur la carte, souvent le soir.','Fiche Google')],
'commerces-multi-sites': [('votre enseigne + votre ville','Un client qui cherche l’adresse la plus proche.','Fiche Google'),('votre enseigne horaires, réserver','Une visite ou une réservation dans l’heure.','Fiche Google'),('meilleur + votre catégorie + votre quartier','Un nouveau client qui ne vous connaît pas encore.','Google')]
}
# Parcours d'une demande : étape, ce qui se passe, qui s'en charge.
JOURNEY = {
'location-de-materiel': [('La recherche','Un artisan tape le matériel et sa ville. Il tombe sur votre page, pas sur celle d’un grand réseau.','SHYFT'),('La demande','Matériel, dates, lieu de livraison : un formulaire simple, ou un appel vers votre agence.','SHYFT'),('La réponse','Disponibilité et devis en quelques minutes, relance si pas de retour. Rien ne reste sans réponse.','SHYFT + vous'),('La location','Votre équipe conclut. La demande est comptée, rattachée à sa source et suivie dans le tableau de bord.','Votre équipe')],
'reseaux-de-franchise': [('La découverte','Un porteur de projet découvre votre enseigne sur Google ou Meta, dans sa région.','SHYFT'),('La candidature','Apport, zone, délai : un formulaire qui qualifie avant de prendre du temps à votre développeur.','SHYFT'),('La qualification','Les profils hors critères sont écartés, les candidats en réflexion sont relancés.','SHYFT + vous'),('Le rendez-vous','Votre développeur reçoit un candidat qualifié, dans le CRM, avec son historique.','Votre équipe')],
'renovation-artisans': [('La recherche','Un propriétaire cherche un artisan pour un projet précis, dans sa commune. Il voit vos réalisations.','SHYFT'),('La demande de devis','Travaux, surface, budget, délai : le formulaire fait le tri avant votre premier appel.','SHYFT'),('La réponse','Un rappel rapide et une visite technique proposée avant que le concurrent ne rappelle.','SHYFT + vous'),('Le chantier','Votre équipe signe. Le devis est suivi jusqu’au chantier, avec sa source et sa valeur.','Votre équipe')],
'immobilier': [('La recherche','Un propriétaire prépare une vente et cherche une estimation dans son quartier.','SHYFT'),('La demande d’estimation','Le bien, le calendrier, les coordonnées : un formulaire qui donne du contexte à votre appel.','SHYFT'),('Le rendez-vous','Prise de rendez-vous d’estimation, relance des propriétaires pas encore décidés.','SHYFT + vous'),('Le mandat','Votre négociateur signe. Le contact est suivi jusqu’à la vente, avec sa source et ses honoraires.','Votre équipe')],
'services-a-domicile': [('La recherche','Une famille cherche une agence proche pour un besoin précis. Elle trouve la vôtre, pas une plateforme.','SHYFT'),('La demande','Besoin, fréquence, adresse : une demande dans votre zone d’intervention, pas ailleurs.','SHYFT'),('L’évaluation','Rappel rapide, rendez-vous d’évaluation, relance organisée si la famille hésite.','SHYFT + vous'),('Le démarrage','Votre agence démarre le service. Chaque nouveau client est compté, par agence et pour le siège.','Votre équipe')],
'commerces-multi-sites': [('La recherche','Un client cherche votre enseigne, ou votre catégorie, près de chez lui. Il tombe sur la bonne adresse.','SHYFT'),('Le contact','Réservation, demande ou itinéraire : un parcours simple depuis la fiche ou la page de l’établissement.','SHYFT'),('La réponse locale','L’établissement répond, l’équipe locale est prévenue, les avis sont suivis.','SHYFT + vous'),('L’achat','Le client vient. Contacts et achats sont rapprochés par point de vente, avec une vue réseau.','Votre équipe')]
}

def market(s):
 rows=''.join(f'<div class="rrow"><div><div class="t">« {q} »</div><div class="d">{why}</div></div><span class="tag info">{channel}</span></div>' for q,why,channel in SEARCHES[s['slug']])
 pains=''.join(f'<li>{p}</li>' for p in s['pain'])
 return f'<section class="block" id="marche"><div class="wrap audit"><div><div class="kicker">Votre marché</div><h2 class="title">{WHO[s["slug"]]}<br>cherchent déjà.</h2><p class="sub">Des exemples de recherches dans votre métier. Et ce qui se passe aujourd’hui quand elles arrivent :</p><ul class="plain">{pains}</ul><a class="btn btn-lime" href="#contact">Recevoir mon audit offert</a></div><div class="report" aria-label="Exemples de recherches de vos futurs clients"><div class="report-head"><b>Ce qu’ils tapent</b><span>Exemples, sans volume</span></div>{rows}</div></div></section>'

def journey(s):
 steps=''.join(f'<div class="step"><div class="n">0{i+1} · {role}</div><h3>{title}</h3><p>{text}</p></div>' for i,(title,text,role) in enumerate(JOURNEY[s['slug']]))
 return f'<section class="block" id="parcours"><div class="wrap"><div class="section-top"><div><div class="kicker">Votre parcours d’acquisition</div><h2 class="title">Du clic<br>à la signature.</h2></div><p class="sub">{DATA[s["slug"]]["follow"]}</p></div><div class="steps">{steps}</div></div></section>'
