const {chromium}=require('/Users/lorenzotrichard/.cache/uv/archive-v0/S2ghcOWcglW9BUt0RjW_E/playwright/driver/package');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));const home='http://localhost:4173';
await page.goto(home,{waitUntil:'networkidle'});await page.screenshot({path:'qa/desktop.png',fullPage:true});
if(!/shyft/i.test(await page.locator('.logo').first().textContent()))throw Error('Logo is not SHYFT');
if(await page.locator('.expertise-list details').count()!==5)throw Error('Expected 5 expertises');
if(await page.locator('#mesure .measure-list article').count()!==5)throw Error('Mesure section incomplete');
await page.locator('.dropdown-toggle').click();await page.locator('.dropdown-menu a').first().click();await page.waitForLoadState('networkidle');if(!await page.locator('select[name="secteur"]').inputValue())throw Error('Sector not prefilled');await page.screenshot({path:'qa/sector.png',fullPage:true});
const sectors=require('../assets/sectors.json');for(const sector of sectors){await page.goto(home+'/secteurs/'+sector.slug+'.html');if(await page.locator('h1').count()!==1)throw Error('Missing title');if(await page.locator('#mesure .metric-grid article').count()!==3)throw Error('Sector measure block missing: '+sector.slug);const opts=await page.locator('select[name="secteur"] option').allTextContents();if(new Set(opts).size!==opts.length)throw Error('Duplicate sector option: '+sector.slug);const broken=await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.src));if(broken.length)await page.waitForLoadState('networkidle');}
for(const legal of ['mentions-legales','confidentialite']){const r=await page.goto(home+'/'+legal+'.html');if(r.status()!==200||await page.locator('h1').count()!==1)throw Error('Legal page missing: '+legal)}
for(const width of [1100,1200]){await page.setViewportSize({width,height:900});await page.goto(home);const ok=await page.evaluate(()=>{const n=document.querySelector('.navigation').getBoundingClientRect(),c=document.querySelector('.nav-cta').getBoundingClientRect();return n.right<=c.left&&document.documentElement.scrollWidth<=innerWidth});if(!ok)throw Error('Navigation overlaps at '+width)}
await page.setViewportSize({width:390,height:844});await page.goto(home,{waitUntil:'networkidle'});await page.screenshot({path:'qa/mobile.png',fullPage:true});await page.locator('.menu-toggle').click();await page.locator('.dropdown-toggle').click();await page.locator('.dropdown-menu a').nth(3).click();await page.waitForLoadState('networkidle');await page.screenshot({path:'qa/sector-mobile.png',fullPage:true});if(await page.locator('select[name="secteur"]').inputValue()!=='Immobilier')throw Error('Wrong sector');await page.locator('[name="nom"]').fill('Test');await page.locator('[name="entreprise"]').fill('Test');await page.locator('[name="email"]').fill('test@example.com');await page.locator('button[type="submit"]').click();await page.locator('#formError').waitFor({state:'visible'});if(await page.locator('.done').isVisible())throw Error('False success');let overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Mobile overflow');if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({errors,overflow,form:'Unconfigured delivery correctly rejected',pages:10}));await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
